package conf.rules;

import com.liaozl.demo.drools.entity.DynamicRuleDto;
import com.liaozl.demo.drools.service.DynamicRuleService;

global DynamicRuleService dynamicRuleService;

rule "dynamicRule_age<18"
    salience 1 // 设置优先级，值越大优先级越高
    no-loop true
    when
        dto:DynamicRuleDto(age<18)
    then
        String str = dynamicRuleService.doRule1Biz(dto);
        dto.setCallRuleResult(str);
        System.out.println("====[age<18]====" + str);
end

rule "dynamicRule_age>=18"
    salience 2 // 设置优先级，值越大优先级越高
    no-loop true
    when
        dto:DynamicRuleDto(age>=18)
    then
        String str = dynamicRuleService.doRule2Biz(dto);
        dto.setCallRuleResult(str);
        System.out.println("====[age>=18]====" + str);
end